export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",

  GET_ALL_USERS_REQUEST: " GET_ALL_USERS_REQUEST",
  GET_ALL_USERS_SUCCESS: " GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAILURE: " GET_ALL_USERS_FAILURE",

  GET_USER_DETAIL_BY_ID_REQUEST: " GET_USER_DETAIL_BY_ID_REQUEST",
  GET_USER_DETAIL_BY_ID_SUCCESS: " GET_USER_DETAIL_BY_ID_SUCCESS",
  GET_USER_DETAIL_BY_ID_FAILURE: " GET_USER_DETAIL_BY_ID_FAILURE",
};

export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: " GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_SUCCESS: " GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAILURE: " GET_ALL_PRODUCT_FAILURE",

  ADD_PRODUCT_REQUEST: " ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: " ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: " ADD_PRODUCT_FAILURE",

  EDIT_PRODUCT_REQUEST: " EDIT_PRODUCT_REQUEST",
  EDIT_PRODUCT_SUCCESS: " EDIT_PRODUCT_SUCCESS",
  EDIT_PRODUCT_FAILURE: " EDIT_PRODUCT_FAILURE",
};

export const categoryConstants = {
  GET_ALL_CATEGORY_REQUEST: " GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: " GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: " GET_ALL_CATEGORY_FAILURE",
};

export const orderConstants = {
  GET_ALL_ORDER_REQUEST: " GET_ALL_ORDER_REQUEST",
  GET_ALL_ORDER_SUCCESS: " GET_ALL_ORDER_SUCCESS",
  GET_ALL_ORDER_FAILURE: " GET_ALL_ORDER_FAILURE",
};

export const saleConstants = {
  GET_ALL_SALE_REQUEST: " GET_ALL_SALE_REQUEST",
  GET_ALL_SALE_SUCCESS: " GET_ALL_SALE_SUCCESS",
  GET_ALL_SALE_FAILURE: " GET_ALL_SALE_FAILURE",
};

export const authenticateConstants = {
  GET_ALL_AUTHENTICATE_REQUEST: " GET_ALL_AUTHENTICATE_REQUEST",
  GET_ALL_AUTHENTICATE_SUCCESS: " GET_ALL_AUTHENTICATE_SUCCESS",
  GET_ALL_AUTHENTICATE_FAILURE: " GET_ALL_AUTHENTICATE_FAILURE",
};

export const analyticConstants = {
  GET_ALL_ANALYTIC_REQUEST: " GET_ALL_ANALYTIC_REQUEST",
  GET_ALL_ANALYTIC_SUCCESS: " GET_ALL_ANALYTIC_SUCCESS",
  GET_ALL_ANALYTIC_FAILURE: " GET_ALL_ANALYTIC_FAILURE",
};
